/**
 * Build Script - Clone File Finder
 * 1. Baca nilai dari .env
 * 2. Generate firebase-config.js (hardcoded, tidak pakai process.env)
 * 3. Obfuscate renderer.js
 * 4. Jalankan electron-builder
 * 5. Hapus file sementara
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// --- STEP 1: Baca .env ---
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const config = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID,
};

// Validasi: pastikan semua key terisi
const missingKeys = Object.entries(config).filter(([k, v]) => !v).map(([k]) => k);
if (missingKeys.length > 0) {
    console.error('\n❌ BUILD GAGAL: Variabel berikut tidak ada di .env:');
    missingKeys.forEach(k => console.error(`   - ${k}`));
    process.exit(1);
}

// --- STEP 2: Generate firebase-config.js ---
const configFilePath = path.join(__dirname, '../firebase-config.js');
const configContent = `// AUTO-GENERATED BY BUILD SCRIPT - JANGAN EDIT MANUAL
// File ini akan terhapus otomatis setelah build selesai
module.exports = ${JSON.stringify(config, null, 2)};
`;

console.log('\n🔧 Step 1: Generating firebase-config.js...');
fs.writeFileSync(configFilePath, configContent);
console.log('   ✅ firebase-config.js berhasil dibuat');

// --- STEP 3: Obfuscate renderer.js ---
console.log('\n🔒 Step 2: Obfuscating renderer.js...');
const rendererSrc = path.join(__dirname, '../renderer.js');
const rendererBackup = path.join(__dirname, '../renderer.original.js');

// Backup dulu
fs.copyFileSync(rendererSrc, rendererBackup);

try {
    execSync(
        `npx javascript-obfuscator renderer.js --output renderer.js --compact true --string-array true --self-defending true`,
        { cwd: path.join(__dirname, '..'), stdio: 'inherit' }
    );
    console.log('   ✅ renderer.js berhasil di-obfuscate');
} catch (err) {
    console.error('   ⚠️  Obfuscation gagal, build tetap dilanjutkan dengan kode original');
    fs.copyFileSync(rendererBackup, rendererSrc);
}

// --- STEP 4: Jalankan electron-builder ---
console.log('\n📦 Step 3: Building .exe...');
try {
    execSync('npx electron-builder -w portable', {
        cwd: path.join(__dirname, '..'),
        stdio: 'inherit'
    });
    console.log('\n✅ BUILD SELESAI! File .exe ada di folder /dist');
} catch (err) {
    console.error('\n❌ electron-builder gagal:', err.message);
}

// --- STEP 5: Hapus file sementara ---
console.log('\n🧹 Step 4: Cleaning up temporary files...');

// Hapus firebase-config.js
if (fs.existsSync(configFilePath)) {
    fs.unlinkSync(configFilePath);
    console.log('   ✅ firebase-config.js dihapus');
}

// Kembalikan renderer.js ke versi original (tidak terobfuscate untuk development)
if (fs.existsSync(rendererBackup)) {
    fs.copyFileSync(rendererBackup, rendererSrc);
    fs.unlinkSync(rendererBackup);
    console.log('   ✅ renderer.js dikembalikan ke versi original');
}

console.log('\n🎉 Proses build selesai!');
